Load SSL library
* Fixes the error:
    SSLError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))
* https://stackoverflow.com/questions/30381581/sslerror-cant-connect-to-https-url-because-the-ssl-module-is-not-available-on