Use HTTP protocol for fetching schedules
* BSEU schedule is mainly available via HTTP protocol
* SSL certificate may suddenly expire like today that would cause issues
* This fixes the following error:

    SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired