Migrate to Google Calendar API v3 (#16)
* Update requirements.txt

* Installs `google-api-python-client`, `google-auth`, `google-auth-oauthlib`, `google-auth-httplib2`, `requests` packages and corresponding Python 2.7 compliant dependencies
* Removes `gdata` package

* Load SSL library

* Fixes the error:
    SSLError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))
* https://stackoverflow.com/questions/30381581/sslerror-cant-connect-to-https-url-because-the-ssl-module-is-not-available-on

* Add `requests-toolbelt` package

* This makes `requests` use the App Engine Requests adapter to use URLFetch
* https://stackoverflow.com/questions/34683437/typeerror-expected-httplib-message-got-type-instance-when-using-requests/46994316#46994316

* Upgrade `lxml` package version

* Update schedule_parser for new schedule structure

* Update deprecated Python SSL lib to 2.7.11

* https://cloud.google.com/appengine/docs/legacy/standard/python/sockets/ssl_support

* Create `ClientConfig` singleton

* This also adds the `gae_env` package

* Replace gdata calendar API w/ Google Calendar API v3